In [2]:
import torch
import numpy as np

In [3]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]
                  ], dtype=np.float32)

In [4]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [9]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [12]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

In [13]:
w, b

(tensor([[ 0.3389, -0.9081,  0.6384],
         [ 0.7080, -0.0653, -0.1933]], requires_grad=True),
 tensor([ 0.5028, -0.0518], requires_grad=True))

In [14]:
def model(x):
    return x @ w.t() + b

In [15]:
# generate predictions
preds = model(inputs)
print(preds)

tensor([[ -8.1475,  38.9497],
        [ -7.7103,  46.2645],
        [-54.6692,  41.5873],
        [ 19.6446,  62.2102],
        [-18.6004,  29.0054]], grad_fn=<AddBackward0>)


In [16]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Loss Function

In [17]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [18]:
loss = mse(preds, targets)
print(loss)

tensor(7798.8564, grad_fn=<DivBackward0>)


In [19]:
# compute gradients
loss.backward()

In [20]:
# gradients for weights
print(w)
print(w.grad)

tensor([[ 0.3389, -0.9081,  0.6384],
        [ 0.7080, -0.0653, -0.1933]], requires_grad=True)
tensor([[-7299.0601, -9430.1953, -5421.5586],
        [-3767.7383, -5340.3667, -3101.4028]])


In [21]:
print(b)
print(b.grad)

tensor([ 0.5028, -0.0518], requires_grad=True)
tensor([-90.0965, -48.3966])


In [24]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [25]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -8.1475,  38.9497],
        [ -7.7103,  46.2645],
        [-54.6692,  41.5873],
        [ 19.6446,  62.2102],
        [-18.6004,  29.0054]], grad_fn=<AddBackward0>)


In [26]:
loss = mse(preds, targets)

In [27]:
loss.backward()

In [28]:
# Adjustg weights & rest gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [29]:
w

tensor([[ 0.4119, -0.8138,  0.6926],
        [ 0.7457, -0.0119, -0.1622]], requires_grad=True)

In [30]:
# calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(5758.2563, grad_fn=<DivBackward0>)


In [31]:
# train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [32]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(470.3975, grad_fn=<DivBackward0>)


In [35]:
# train for 5000 epochs
for i in range(5000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [36]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5215, grad_fn=<DivBackward0>)


# Linear regression using PyTorch builtins

In [37]:
import torch.nn as nn

In [38]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [39]:
from torch.utils.data import TensorDataset

In [40]:
# define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [41]:
type(train_ds)

torch.utils.data.dataset.TensorDataset

In [42]:
from torch.utils.data import DataLoader

In [43]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [44]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [103.,  43.,  36.],
        [ 91.,  87.,  65.],
        [ 73.,  66.,  44.],
        [ 88., 134.,  59.]])
tensor([[ 22.,  37.],
        [ 20.,  38.],
        [ 80., 102.],
        [ 57.,  69.],
        [118., 132.]])


In [45]:
# define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3523, -0.3834,  0.0591],
        [-0.2365, -0.5384,  0.4301]], requires_grad=True)
Parameter containing:
tensor([ 0.2535, -0.2397], requires_grad=True)


In [48]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3523, -0.3834,  0.0591],
         [-0.2365, -0.5384,  0.4301]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2535, -0.2397], requires_grad=True)]

In [49]:
preds = model(inputs)
print(preds)

tensor([[  2.8294, -35.0780],
        [  2.3620, -41.6080],
        [-17.0372, -68.0079],
        [ 21.8928, -31.5952],
        [ -8.1012, -38.1321],
        [  3.5651, -34.7761],
        [  2.8045, -40.6395],
        [-16.6257, -67.8143],
        [ 21.1571, -31.8971],
        [ -8.3944, -37.4656],
        [  3.2719, -34.1096],
        [  3.0977, -41.3061],
        [-17.4797, -68.9764],
        [ 22.1860, -32.2618],
        [ -8.8369, -38.4341]], grad_fn=<AddmmBackward>)


In [50]:
import torch.nn.functional as F

In [51]:
# define loss function
loss_fn = F.mse_loss

In [54]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(14076.6553, grad_fn=<MseLossBackward>)


In [55]:
# Optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [57]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [61]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 0.8763
Epoch [20/100], Loss: 0.9286
Epoch [30/100], Loss: 0.8869
Epoch [40/100], Loss: 0.9726
Epoch [50/100], Loss: 1.5351
Epoch [60/100], Loss: 1.5518
Epoch [70/100], Loss: 1.2957
Epoch [80/100], Loss: 0.8779
Epoch [90/100], Loss: 1.1583
Epoch [100/100], Loss: 1.0983


In [62]:
preds = model(inputs)
print(preds)

tensor([[ 56.9772,  70.3259],
        [ 81.9897, 100.5292],
        [118.1496, 132.7541],
        [ 20.7950,  37.7353],
        [101.8573, 118.4591],
        [ 55.7288,  69.2497],
        [ 81.8458, 100.6273],
        [118.4408, 133.3598],
        [ 22.0434,  38.8115],
        [102.9618, 119.6334],
        [ 56.8333,  70.4240],
        [ 80.7413,  99.4529],
        [118.2934, 132.6560],
        [ 19.6905,  36.5609],
        [103.1057, 119.5353]], grad_fn=<AddmmBackward>)


In [63]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])
